# theme: jekyll-theme-minimal
theme: jekyll-theme-basically-basic
title: phlpphns.github.io
description: Maybe you find something ineresting on my github account. For example a template for CV and a thesis in LaTeX. Also, I provide a couple of tools for scientific data analyis there (more to come!).

tags: [
  "Git","GitHub Pages","Branches","Commits","Pull Requests"
]
